version: '3.3'

services:
  apache:
    build: ./apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/data:/var/www/html:rw
    networks:
      - wampnet
  
  mariadb:
    image: mariadb:10.4.6
    #restart: always
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wampnet

  adminer:
    image: adminer:4
    #restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    networks:
      - wampnet

volumes:
  homepage:

networks:
  wampnet:
    driver: bridge
