version: '3.3'

services:
  apache:
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    #volumes:
      #- ./apache/data:/usr/local/apache2/htdocs:rw
    networks:
      - test

volumes:
  homepage:

networks:
  test:
    driver: bridge
