<?php

/*  DAlbum Norvegian language support file

    (c) Copyright 2003 by DeltaX Inc.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'          => 'Logg inn',
    'loginBtnTitle'     => 'Logg inn',

    'logoutBtn'         => 'Logg ut',
    'logoutBtnTitle'    => 'Logg ut',

    'reindexBtn'        => 'Reindekser',
    'reindexBtnTitle'   => 'S&oslash;k etter nye bilder og oppdater DAlbum databasen',

    'usrmgrBtn'         => 'Brukere',
    'usrmgrBtnTitle'    => 'Legg til/fjern brukere og endre passord',

    'closeWindowBtn'    => 'Lukk vindu',
    'closeWindowBtnTitle'=> 'Lukk dette vinduet',

    'fullScreenBtn'         => 'Fullskjerm',
    'fullScreenBtnTitle'    => '&Aring;pne vinduet i ett fullskjermvindu. Eller bare trykk F11 for samme effekten',

    'editDefBtn'            => 'Endre',
    'editDefBtnTitle'       => 'Endre album tittel, kommentarer eller h&aring;ndtere blidene for albumet',

    'indexUsername'         => 'Bruker:',
    'page'                  => 'Viser #begin# - #end# av #count#. &nbsp; side: &nbsp;',
    'noimages'              => 'Ingen bilder',
    'noPublicImages'        => 'Ingen offentlige bilder tilgjengelig. Vennligst logg inn.',
    'noscript'              => 'Beklager, katalogvisning kan bare benyttes med Javasscript slått på for nettleseren.<BR><BR>Vennligst endre innstilingene i din nettleser.',

    'prevPageBtn'           => 'Forrige',
    'prevPageBtnTitle'      => 'G&aring; til forrige side (#page#)',

    'nextPageBtn'           => 'Neste',
    'nextPageBtnTitle'      => 'G&aring; til neste side (#page#)',

    'statusLeft'            => '<b>#TotalImages#</b> bilder i <b>#TotalAlbums#</b> album',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'              => 'Til hovedsiden',
    'username'              => 'Brukernavn:',
    'password'              => 'Passord:',
    'bytes'                 => 'bytes',
    'KB'                    => 'KB',
    'MB'                    => 'MB',
    'pixels'                => 'pixels',
    'errorReturn'           => 'Til forrige side',

    /// Login.php
    'loginTitle'            =>  'Logg inn p&aring; #title#',
    'loginAuthError'        =>  'Autentifiseringsfeil',
    'loginBadUserName'      =>  'Ditt brukernavn eller passord finnes ikke i databasen.',
    'loginAgain'            =>  'Logg inn igjen',
    'loginNoCookiesWarning' =>  '<HR><B>Advarsel: Sm&aring; (Cookies) er avsl&aring;tt av i din nettleser!</B><BR>For &aring; fortsette m&aring; dette sl&aring;s p&aring;.<BR>Vennligst sl&aring; p&aring; dette i instillingen for din nettleser og oppfrisk dene siden.<BR><HR>',
    'loginLoginBtn'         => 'Logg inn',
    'loginCancelBtn'        => 'Avbryt',

    // pass.php
    'passTitle'             => 'Brukerh&aring;ndterer',
    'passUserExists'        => 'Brukeren #user# eksisterer allerede.',
    'passNotMatch'          => 'Passordene er ikke like.',
    'passNoUserSelected'    => 'Ingen bruker er valgt.',
    'passNoAdminDelete'     => 'DAlbum hovedadministrator kan ikke slettes.',
    'passWriteError'        => 'Kan ikke &aring;pne passordfil for skriving!',
    'passError'             => '<B>Feil: </B>#error#',
    'passAddBtn'            => 'Legg til',
    'passDeleteBtn'         => 'Slett',
    'passChangePwdBtn'      => 'Forandre passord',
    'passCloseBtn'          => 'Lukk',
    'passCancelBtn'         => 'Avbryt',

    'passAddUserDlgTitle'   => 'Legg til bruker',
    'passChangePwdDlgTitle' => 'Forandre passord',
    'passConfirmPassword'   => 'Bekreft passord:',

    // showimg.php
    'showPrevBtn'           => 'Forrige',
    'showPrevBtnTitle'      => 'Vis forrige bilde',

    'showNextBtn'           => 'Neste',
    'showNextBtnTitle'      => 'Vis neste bilde',

    'showIndexBtn'          => 'Indeks',
    'showIndexBtnTitle'     => 'Returner til albumets indeks',

    'showImageBtn'          => 'Vis bilde',
    'showImageBtnTitle'     => 'Vsi bare bilder i nytt vindu',

    'showHiResBtn'          => 'Opprinnelig bilde (#size#)',
    'showHiResBtnTitle'     => 'Vis opprinnelig bilde i h&oslash;y oppl&oslash;sning i nytt vindu',

    'showShowDetailsBtn'        => 'Vis detaljer',
    'showShowDetailsBtnTitle'   => 'Vis EXIF\'s bildedetaljer:: bildedato, lukningshastighet osv. (om tilgjengelig)',

    'showHideDetailsBtn'        => 'Gjem detaljer',
    'showHideDetailsBtnTitle'   => 'Gjem EXIF\'s bildedetaljer',

    'showRotateBtn'             => 'Roter',
    'showRotateBtnTitle'        => 'Roter bilde 90 grader med kloken',

    'showUpdateBtn'             => 'Oppdater',
    'showUpdateBtnTitle'        => 'Generer p&aring; nytt sm&aring;bilder og omgjorte bilder',

    'showExifFilename'          => 'Filnavn: ',
    'showExifFilesize'          => 'Filst&oslash;rrelse: ',
    'showExifResolution'        => 'Oppl&oslash;sning: ',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => 'Dato: ',
    'showExifCamera'            => 'Kamera modell: ',
    'showExifExposure'          => 'Utl&slash;sertid: ',
    'showExifAperture'          => 'Linsest&oslash;rrelse: ',
    'showExifFocalLength'       => 'Fokuseringstid: ',
    'showExifFlashYes'          => 'Ja',
    'showExifFlashNo'           => 'Nei',
    'showExifFlash'             => 'Blitz: ',
    'showExifDialogTitle'       => 'Opprinnelige detaljer for bilde',

    'showImageTitleImage'       => 'Klikk for &aring; vise neste bilde: #image#',
    'showImageTitleIndex'       => 'Klikk for &aring; returnere til albumets indeks',


    // edit*.php
    'editTitle'                 => 'Endre #filename#',
    'editDlgTitle'              => 'Albumets definisjionsfil',
    'editFileLocation'          => 'Filplassering',

    'editEditAsTextBtn'         => 'Endre som tekst',
    'editEditAsTextBtnTitle'    => 'Endre denne filen som en ren tekstfil',
    'editReindexNote'           => 'Vennligst bemerk, at du m&aring; reindeksere etter &aring; ha forandret instillingene for bildest&oslash;rrelse',

    'editAlbumTitle'            => 'Albumets tittel:',
    'editAlbumDate'             => 'Dato:',
    'editAlbumComment'          => 'Kommentar:',
    'editAlbumTitleImage'       => 'Hovedbilde:',
    'editAlbumDefault'          => 'Standard album',
    'editAlbumUsers'            => 'Tillatte brukere:',
    'editAlbumUsersNote'        => '(komma-separert brukerliste, tom tekst-streng eller <B>alle</B> = anonym tilgang, <B>gyldig bruker</B>=alle autentifiserte brukere)',

    'editCancelBtn'             => 'Avbryt',
    'editSaveBtn'               => 'Lagre',

    'editThumbLink'             => '#filename# (&Aring;pner i nytt vindu)',
    'editImgFilename'           => 'Filnavn<BR><small>(forandre for &aring; bytte navn, nuttstill for og slette)</small>:',
    'editImgTitle'              => 'Tittel:',
    'editImgComment'            => 'Kommentar:',
    'editImgResize'             => 'Gi bildet ny st&oslash;rrelse',
    'editNewFileMessage'        => '( ny fil )',
    'editTop'                   => 'Topp',

    'editRenameError'           => 'Kunne ikke endre filnavnet til #filename# - feil filendelse',
    'editSaveError'             => 'En feil skjedde med lagring av albumets definisjonsfil #filename#',
    'editHTML'                  => 'HTML',
    'editText'                  => 'Tekst',

    // reindex.php
    'reindexTitle'              => 'DAlbum reindekserer',
    'reindexDlgTitle'           => 'DAlbum reindekserer',
    'reindexDlgComment'         => 'DAlbum reindeksering s&oslash;ker etter kataloger for nye bilder, lager sm&aring;bilder og oppdaterer bilde-databasen.',
    'reindexDlgSpeed'           => 'Vennligst spesifiser reindekseringens hastighet:',

    'reindexSpeed0'             => '<B>Rask</B>. Lager bare ikke-eksisterende sm&aring;bilder og omgj&oslash;r bilder. Verifiserer ikke bildenes integritet.',
    'reindexSpeed1'             => '<B>Moderat</B>.  Lager bare ikke-eksisterende eller korruptesm&aring;bilder og omgj&oslash; bilder. Verifiserer bildenes integritet.',
    'reindexSpeed2'             => '<B>Sen</B>. Samme som <B>Moderat</B> ,men sletter ogs&aring; ikke-eksisterende bilde-referanser (sm&aring;bilder og omgjorte).',
    'reindexSpeed3'             => '<B>Veldig sen</B>. Lager alle sm&aring;bilder og omgj&oslash;r alle bilder p&aring; nytt. Advaresl: dette kan ta mange timer!',

    'reindexCancelBtn'          => 'Avbryt',
    'reindexStartBtn'           => 'Start',

    'reindexProgressTitle'      => 'DAlbum reindeksering p&aring;g&aring;r',

    'reindexError'              => 'En feil skjedde under opprettelse av sm&aring;bilde',
    'reindexRetry'              => 'Pr&oslash;v p&aring; nytt p&aring; feilet bilde',
    'reindexIgnore'             => 'Ignorer feil og fortsett',
    'reindexAgain'              => 'Start reindeksering p&aring; nytt',

    'reindexMainImageProblem'   => 'Opplastet bilde har et problem',
    'reindexResizedProblem'     => 'Omgjort bilde har et problem',
    'reindexThumbProblem'       => 'Problem med sm&aring;bilde',

    'reindexCompleted'          => '<P>Operasjon fullf&oslash;rt.</P><P>Reindeksering tok #elapsed# sekunder. Album ble generert p&aring; #treeelapsed# sekunder.</P>',
    'reindexStats'              => 'DAlbum statistikk',
    'reindexStatsAlbums'        => 'Antall album:',
    'reindexStatsImages'        => 'Antall bilder:',
    'reindexStatsOrigSize'      => 'Total st&oslash;rrelse for opprinnelige bilder:',
    'reindexStatsResizedSize'   => 'Total st&oslash;rrelse for omgjorte bilder:',
    'reindexStatsThumbSize'     => 'Total st&oslash;rrelse for sm&aring;bilder:',

    'reindexStatusErrors'       => '<B>Status: </B> #errors# feil funnet:',

    'reindexStatusOK'           => '<B>Status: </B> Suksess. Ingen feil.',
    'reindexSaveError'          => '<B>Feil: </B>Kunne ikke lagre #filename#',

    'reindexTHFilename'         => 'Filnavn',
    'reindexTHProblem'          => 'Problem',

    ''  => ''
);

?>
