<?php

/*  DAlbum Chinese-UTF-8 language support file

    (c) Copyright 2003 by DeltaX Inc.

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
    OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    ITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

$newlang=array(

    ///////////////////////////////
    // Index.php
    ///////////////////////////////
    'loginBtn'      => '��¼',
    'loginBtnTitle'     => '��¼',

    'logoutBtn'         => 'ע��',
    'logoutBtnTitle'    => 'ע��',

    'reindexBtn'        => '�ؽ�����',
    'reindexBtnTitle'   => '��Ѱ�µ�ͼƬ�������� DAlbum ���ݿ�',

    'usrmgrBtn'         => '�û�',
    'usrmgrBtnTitle'    => '�������Ƴ��û�����ı�����',

    'closeWindowBtn'    => '�ر�ȫ��Ļ',
    'closeWindowBtnTitle'   => '�ر�ȫ��Ļ',

    'fullScreenBtn'     => 'ȫ��Ļ',
    'fullScreenBtnTitle'    => '��ȫ��Ļ������ҳ��Ч���밴 F11 ��ͬ',

    'editDefBtn'        => '�༭',
    'editDefBtnTitle'   => '�޸��ಾ���ƣ��������Լ������ಾ�ڵ�ͼƬ��',

    'indexUsername'     => '�û���',
    'page'          => '��ʾ�� #begin# - #end# ����Ŀ���ܹ��� #count# ����Ŀ��&nbsp;ҳ����',
    'noimages'      => 'û��ͼƬ',
    'noPublicImages'    => 'û�й�����ͼƬ�����¼��',
    'noscript'      => '�Բ��������������Ҫ���� Javascript �Ĺ��ܣ�������ʾ��״Ŀ¼��<BR><BR>���������ѡ����˹��ܡ�',

    'prevPageBtn'           => '&lt;&lt;',
    'prevPageBtnTitle'      => '#page#',

    'nextPageBtn'           => '&gt;&gt;',
    'nextPageBtnTitle'      => '(#page#)',
    'statusLeft'            => '���� <b>#TotalImages#</b> �ֱ�ͼƬ����� <b>#TotalAlbums#</b> ���ಾ',
    'statusRight'           => '<a href="http://www.dalbum.org">Generated by DAlbum #version# &copy; 2003 DeltaX Inc. in #elapsed# s</a>',

    // Common stuff
    'mainPage'          => '�ص���ҳ',
    'username'          => '�û����ƣ�',
    'password'          => '���룺',
    'bytes'             => '�ֽ�',
    'KB'                => 'KB',
    'MB'                => 'MB',
    'pixels'            => '����',
    'errorReturn'           => '�ص���һҳ',

    /// Login.php
    'loginTitle'            => '��¼�� #title#',
    'loginAuthError'        => '��֤����',
    'loginBadUserName'      => '�û����ƻ��������',
    'loginAgain'            => '���µ�¼',
    'loginNoCookiesWarning'     =>  '<HR><B>���棺����������ѹص� Cookies ���ܣ�</B><BR>���������ѡ��� Cookies ���ܣ�������������ҳ��<BR><HR>',
    'loginLoginBtn'         => '����',
    'loginCancelBtn'        => 'ȡ��',

    // pass.php
    'passTitle'         => '�û�����',
    'passUserExists'        => '#user# �Ѿ�����',
    'passNotMatch'          => '���벻��ȷ',
    'passNoUserSelected'        => 'û��ѡ���û�',
    'passNoAdminDelete'     => '����ɾ����Ҫ�� DAlbum ����Ա��',
    'passWriteError'        => '�޷�д�������ļ���',
    'passError'             => '<B>����</B>#error#',
    'passAddBtn'            => '����',
    'passDeleteBtn'         => 'ɾ��',
    'passChangePwdBtn'      => '��������',
    'passCloseBtn'          => '�ر�',
    'passCancelBtn'         => 'ȡ��',

    'passAddUserDlgTitle'       => '�����û�',
    'passChangePwdDlgTitle'     => '��������',
    'passConfirmPassword'       => 'ȷ�����룺',

    // showimg.php
    'showPrevBtn'           => '��һҳ',
    'showPrevBtnTitle'      => '��ʾ��һ��ͼƬ',

    'showNextBtn'           => '��һҳ',
    'showNextBtnTitle'      => '��ʾ��һ��ͼƬ',

    'showIndexBtn'          => 'Ŀ¼',
    'showIndexBtnTitle'         => '�ص��ಾĿ¼',

    'showImageBtn'          => '�´�����ʾͼƬ',
    'showImageBtnTitle'         => '���´�������ʾͼƬ',

    'showHiResBtn'          => 'ԭ��СͼƬ (#size#)',
    'showHiResBtnTitle'         => '���´�������ʾԭ�и߷ֱ��ʵ�ͼƬ',

    'showShowDetailsBtn'        => '��ʾ��ϸ����',
    'showShowDetailsBtnTitle'   => '��ʾͼƬ�� EXIF ��ϸ���ݣ�ͼƬ���ڣ������ٶȵȵȣ����У���',

    'showHideDetailsBtn'        => '������ϸ����',
    'showHideDetailsBtnTitle'   => '����ͼƬ�� EXIF ��ϸ����',

    'showRotateBtn'         => '��ת',
    'showRotateBtnTitle'        => '��ͼƬ˳ʱ������������ת',

    'showExifFilename'      => '�ļ����ƣ�',
    'showExifFilesize'      => '������С��',
    'showExifResolution'        => '�ֱ��ʣ�',
    'showExifDateFormat'        => '%a, %d %B %Y %H:%M:%S',
    'showExifDate'              => '���ڣ�',
    'showExifCamera'            => '����ͺţ�',
    'showExifExposure'          => '�ع�ʱ�䣺',
    'showExifAperture'          => '��Ȧ��С��',
    'showExifFocalLength'       => '���ࣺ',
    'showExifFlashYes'          => '��',
    'showExifFlashNo'           => 'û��',
    'showExifFlash'             => 'ʹ������ƣ�',
    'showExifDialogTitle'       => 'ͼƬ��ϸ����',

    'showImageTitleImage'       => '�밴�˴�����ʾ��һ��ͼƬ: #image#',
    'showImageTitleIndex'       => '�밴�˴��Իص��ಾĿ¼',


    // edit*.php
    'editTitle'         => '�༭ #filename#',
    'editDlgTitle'          => '�ಾ���嵵��',
    'editFileLocation'      => '����λ��',

    'editEditAsTextBtn'     => '�Դ����ֱ༭',
    'editEditAsTextBtnTitle'    => '�Դ����ֱ༭�˵���',
    'editReindexNote'       => '��ע�⣺�ڸ���ͼƬ�Ĵ�С�趨���������ؽ�������',

    'editAlbumTitle'            => '�ಾ���ƣ�',
    'editAlbumDate'             => '���ڣ�',
    'editAlbumComment'          => '������',
    'editAlbumTitleImage'           => '����ͼƬ��',
    'editAlbumDefault'          => '�Ƿ�ΪԤ���ಾ��',
    'editAlbumUsers'            => '�����ۿ����û���',
    'editAlbumUsersNote'        => '(comma-separated user list, empty string or <B>all</B> = anonymous access, <B>valid-user</B>=any authenticated user)',

    'editCancelBtn'             => 'ȡ��',
    'editSaveBtn'               => '����',

    'editThumbLink'             => '#filename# �����´��ڿ�����',
    'editImgFilename'           => '�ļ�����<BR><small>�������ַ����������ļ�����ɾ���ַ�����ɾ��������</small>:',
    'editImgTitle'              => '���ƣ�',
    'editImgComment'            => '������',
    'editImgResize'             => '����ͼƬ��С',
    'editNewFileMessage'            => '���µ�����',
    'editTop'               => '�ص�����',

    'editRenameError'           => '�޷����ļ����Ƹ��ĳ� #filename# ����Ч����չ��',
    'editSaveError'             => '�����ಾ���嵵�� #filename# ʱ��������',
    'editHTML'                  => 'HTML',
    'editText'                  => '������',

    // reindex.php
    'reindexTitle'              => 'DAlbum �ؽ�����',
    'reindexDlgTitle'           => 'DAlbum �ؽ�����',
    'reindexDlgComment'         => 'DAlbum �ؽ�������ϵͳ�������ݼ���Ѱ�µ�ͼƬ��������©��ͼƬԤ����������ͼƬ���ݿ⡣',
    'reindexDlgSpeed'           => '��ѡ���ؽ��������ٶȣ�',

    'reindexSpeed0'             => '<B>��</B>��ֻ���������ڵ�ͼƬԤ������СͼƬ��������ͼƬ�������ԡ�',
    'reindexSpeed1'             => '<B>һ��</B>��ֻ���������ڻ��𻵵�ͼƬԤ������СͼƬ�����ͼƬ�������ԡ�',
    'reindexSpeed2'             => '<B>��</B>���� <B>һ��</B> ������ͬ������ɾ����û�й�����ͼƬԤ������С��ͼƬ��',
    'reindexSpeed3'             => '<B>����</B>�����½���ͼƬԤ������СͼƬ�����棺������Ҫ��Сʱ��',

    'reindexCancelBtn'          => 'ȡ��',
    'reindexStartBtn'           => '��ʼ',

    'reindexProgressTitle'      => 'DAlbum �ؽ������С�',

    'reindexError'              => '����ͼƬԤ��ʱ��������',
    'reindexRetry'              => '���Դ����ͼƬ',
    'reindexIgnore'             => '���Դ��󲢼���',
    'reindexAgain'              => '��ͷ��ʼ�ؽ�����',

    'reindexMainImageProblem'   => 'ͼƬ����',
    'reindexResizedProblem'     => '��СͼƬ����',
    'reindexThumbProblem'       => 'ͼƬԤ������',

    'reindexCompleted'          => '<P>��ɡ�</P><P>�ؽ�������ʹ���� #elapsed# �룬�������� #treeelapsed# �������ಾ��״�ṹ��</P>',
    'reindexStats'              => 'DAlbum ����ͳ��',
    'reindexStatsAlbums'        => '�ಾ��Ŀ��',
    'reindexStatsImages'        => 'ͼƬ��Ŀ��',
    'reindexStatsOrigSize'      => 'ԭͼƬ�ܴ�С��',
    'reindexStatsResizedSize'   => '��СͼƬ�ܴ�С��',
    'reindexStatsThumbSize'     => 'ͼƬԤ���ܴ�С��',

    'reindexStatusErrors'       => '<B>״̬�� </B> ���ҵ� #errors# ������',

    'reindexStatusOK'           => '<B>״̬��</B> �ɹ���û�з����κδ���',
    'reindexSaveError'          => '<B>����</B> �޷����� #filename#',

    'reindexTHFilename'         => '�ļ�����',
    'reindexTHProblem'          => '����',

    ''  => ''
);

?>
